// Generated by scripts/generate-fixture-sources.mjs. Do not edit by hand.
import type { SourceFile } from '@/lib/domain/schemas'

export const DEMO_SOURCES: SourceFile[] = [
  {
    "path": "contracts/IPool.sol",
    "content": "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\ninterface IPool {\n    function getReserves() external view returns (uint112 reserveCollateral, uint112 reserveDebt);\n}\n"
  },
  {
    "path": "contracts/LendingVault.sol",
    "content": "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\nimport {SpotPriceOracle} from \"./SpotPriceOracle.sol\";\n\ninterface IERC20 {\n    function transfer(address to, uint256 amount) external returns (bool);\n}\n\n/// @notice ETH-collateralised lending vault that issues a debt token.\ncontract LendingVault {\n    uint256 public constant COLLATERAL_FACTOR_BPS = 7_500;\n\n    SpotPriceOracle public immutable oracle;\n    IERC20 public immutable debtToken;\n\n    mapping(address => uint256) public collateral;\n    mapping(address => uint256) public debt;\n\n    constructor(address oracle_, address debtToken_) {\n        oracle = SpotPriceOracle(oracle_);\n        debtToken = IERC20(debtToken_);\n    }\n\n    function depositCollateral() external payable {\n        collateral[msg.sender] += msg.value;\n    }\n\n    function collateralValue(address account) public view returns (uint256) {\n        return (collateral[account] * oracle.getPrice()) / 1e18;\n    }\n\n    function maxBorrow(address account) public view returns (uint256) {\n        return (collateralValue(account) * COLLATERAL_FACTOR_BPS) / 10_000;\n    }\n\n    function borrow(uint256 amount) external {\n        require(debt[msg.sender] + amount <= maxBorrow(msg.sender), \"insufficient collateral\");\n        debt[msg.sender] += amount;\n        require(debtToken.transfer(msg.sender, amount), \"transfer failed\");\n    }\n\n    function withdrawCollateral(uint256 amount) external {\n        require(collateral[msg.sender] >= amount, \"insufficient collateral\");\n        uint256 remainingValue = ((collateral[msg.sender] - amount) * oracle.getPrice()) / 1e18;\n        require(debt[msg.sender] <= (remainingValue * COLLATERAL_FACTOR_BPS) / 10_000, \"undercollateralized\");\n\n        (bool ok, ) = msg.sender.call{value: amount}(\"\");\n        require(ok, \"ETH transfer failed\");\n\n        collateral[msg.sender] -= amount;\n    }\n}\n"
  },
  {
    "path": "contracts/RewardDistributor.sol",
    "content": "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\n/// @notice Pays accrued ETH rewards to stakers.\ncontract RewardDistributor {\n    address public immutable owner;\n    mapping(address => uint256) public accrued;\n\n    modifier onlyOwner() {\n        require(msg.sender == owner, \"not owner\");\n        _;\n    }\n\n    constructor() payable {\n        owner = msg.sender;\n    }\n\n    function accrue(address account, uint256 amount) external onlyOwner {\n        accrued[account] += amount;\n    }\n\n    function claim() external {\n        uint256 reward = accrued[msg.sender];\n        accrued[msg.sender] = 0;\n        payable(msg.sender).send(reward);\n    }\n}\n"
  },
  {
    "path": "contracts/SpotPriceOracle.sol",
    "content": "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\nimport {IPool} from \"./IPool.sol\";\n\n/// @notice Prices collateral from the spot reserves of a single AMM pool.\ncontract SpotPriceOracle {\n    address public owner;\n    IPool public pool;\n\n    event PoolUpdated(address indexed previousPool, address indexed newPool);\n\n    constructor(address initialPool) {\n        owner = msg.sender;\n        pool = IPool(initialPool);\n    }\n\n    function setPool(address newPool) external {\n        emit PoolUpdated(address(pool), newPool);\n        pool = IPool(newPool);\n    }\n\n    /// @return price Collateral price denominated in the debt asset, 18 decimals.\n    function getPrice() external view returns (uint256 price) {\n        (uint112 reserveCollateral, uint112 reserveDebt) = pool.getReserves();\n        require(reserveCollateral > 0, \"empty pool\");\n        price = (uint256(reserveDebt) * 1e18) / uint256(reserveCollateral);\n    }\n}\n"
  },
  {
    "path": "contracts/Treasury.sol",
    "content": "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\n/// @notice Protocol fee treasury.\ncontract Treasury {\n    address public owner;\n\n    constructor() {\n        owner = msg.sender;\n    }\n\n    function sweep(address payable to) external {\n        require(tx.origin == owner, \"not owner\");\n        to.transfer(address(this).balance);\n    }\n\n    receive() external payable {}\n}\n"
  }
]
